[supervisord]
nodaemon=true

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true

[program:mqtt-listener]
command=php /var/www/artisan mqtt:listen
autostart=true
autorestart=true
stderr_logfile=/var/www/storage/logs/mqtt.err.log
stdout_logfile=/var/www/storage/logs/mqtt.out.log